baseURL: "https://ninanikiforova.org/" 
title: Nina Nikiforova
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

social:
    twitter: nikiforovannina

taxonomies:
    tag: tags 

params:
    description: |
        Hi! I'm a fourth-year PhD Econ student at Bocconi University. My research interests lie in the fields of political economy and applied industrial organization. 
        You can reach me at <a href="mailto:nina.nikiforova@phd.unibocconi.it">nina.nikiforova@phd.unibocconi.it</a>. 
         <br><br><br>
        My CV is [here](cv.pdf).    
    author: Nina Nikiforova
    author: Nina Nikiforova
    googleAnalyticsID: 
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    math: true
    profileMode:
          enabled: true
          title: Nina Nikiforova
          subtitle: | 
              Hi! I'm a fourth-year PhD Econ student at Bocconi University. My research interests lie in the fields of political economy and applied industrial organization. 
              You can reach me at <a href="mailto:nina.nikiforova@phd.unibocconi.it">nina.nikiforova@phd.unibocconi.it</a>. 
               <br><br><br>
              My CV is [here](cv.pdf).    
          author: Nina Nikiforova 
          imageUrl: "/IMAGE2.jpg"
          #imageWidth: 160
          imageHeight: 200
          imageTitle: 
          buttons:
            - name: about
              url: /about/
            - name: research
              url: /research/
            - name: contact
              url: /contact/
              
    socialIcons:
        - name: CV
          url: "/cv.pdf"
        - name: Email
          url: "mailto:nina.nikiforova@phd.unibocconi.it"
        - name: Twitter
          url: "https://twitter.com/nikiforovannina"

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Nina Nikiforova"
      icon: "/apple-touch-icon.png"
      iconHeight: 35
      
      markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

