baseURL: "https://ninanikiforova.org/" 
title: Nina Nikiforova
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

social:
    twitter: nikiforovannina

taxonomies:
    tag: tags 

params:
    description: Welcome! I'm a second year PhD Econ student at Bocconi Univerisity and interested in political economy. 
    author: Nina Nikiforova
    googleAnalyticsID: 
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    math: true
    profileMode:
          enabled: true
          title: Nina Nikiforova
          subtitle: Welcome! I'm a second year PhD Econ student at Bocconi Univerisity and interested in political economy. 
          imageUrl: "/IMAGE.jpg"
          imageWidth: 150
          imageHeight: 150
          imageTitle: 
          buttons:
            - name: about
              url: /about/
            - name: research
              url: /research/
            - name: contact
              url: /contact/
              
    socialIcons:
        - name: CV
          url: "/cv.pdf"
        - name: Email
          url: "mailto:nina.nikiforova@phd.unibocconi.it"
        - name: Twitter
          url: "https://twitter.com/nikiforovannina"

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Nina Nikiforova"
      icon: "/apple-touch-icon.png"
      iconHeight: 35
      
      markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

