baseURL: "https://ninanikiforova.org/" 
title: Nina Nikiforova
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

social:
    twitter: nikiforovannina

taxonomies:
    tag: tags 


params:
    description: "I'm a second year PhD econ student at Bocconi Univerisity. Political econ, autocracies, collective memory and others"
    author: Nina Nikiforova
    googleAnalyticsID: 
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Nina Nikiforova
          subtitle:  "I'm a second year PhD econ student at Bocconi Univerisity. Political econ, autocracies, collective memory and others"
          imageUrl: "/IMAGE.jpg"
          imageWidth: 100
          imageHeight: 150
          imageTitle: 
        
    socialIcons:
        - name: CV
          url: "https://www.dropbox.com/s/rxwdt79olifl6o7/cv.pdf?dl=0"
        - name: Email
          url: "mailto:nina.nikiforova@phd.unibocconi.it"
        - name: Location
          url: /location/
        - name: Twitter
          url: "https://twitter.com/nikiforovannina"

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Nina Nikiforova"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
