baseURL: "https://ninanikiforova.org/" 
title: Nina Nikiforova
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

social:
    twitter: nikiforovannina

taxonomies:
    tag: tags 


params:
    description: Hey! I'm a second year PhD Econ student at Bocconi Univerisity. I am interested in topics spanning the literature of political economy and political science, such as authoritarianism, collective actions problems, collective memory and others. Before starting my PhD I earned MA in economics from New Economic School in Moscow and BSc and MSc in Geography from Moscow State Univerisy.
    author: Nina Nikiforova
    googleAnalyticsID: 
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: false
    disableScrollToTop: false
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Nina Nikiforova
          subtitle:  Hey! I'm a second year PhD Econ student at Bocconi Univerisity.I am interested in topics spanning the literature of political economy and political science, such as authoritarianism, collective actions problems, collective memory and others. Before starting my PhD I earned MA in economics from New Economic School in Moscow and BSc and MSc in Geography from Moscow State Univerisy.
          imageUrl: "/IMAGE.jpg"
          imageWidth: 150
          imageHeight: 150
          imageTitle: 
    
    
    
    socialIcons:
        - name: CV
          url: "/cv.pdf"
        - name: Email
          url: "mailto:nina.nikiforova@phd.unibocconi.it"
        - name: Twitter
          url: "https://twitter.com/nikiforovannina"

    assets:
        disableHLJS: true
        #disableScrollBarStyle: true
        
    cover:
        hiddenInList: true
        hiddenInSingle: true
   
    
    label:
      text: "Nina Nikiforova"
      icon: "/apple-touch-icon.png"
      iconHeight: 35

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 2
    - identifier: teaching
      name: Teaching
      url: /teaching/
      weight: 3
    - identifier: search
      name: Search
      url: /search/
      weight: 4
      
pygmentsUseClasses: true

markup:
  tableOfContents:
    # Without this, Hugo ToC doesn't show h4 and higher
    # https://github.com/alex-shpak/hugo-book/issues/52
    endLevel: 6

 highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    # highlight.js also doesn't use line numbers by default.
    # The rationale is that doing so improves readability
    # (https://highlightjs.readthedocs.io/en/latest/line-numbers.html).
    # Therefore, I disable it by default.
    # Note: It's possible to enable it on a specific code block by specifying
    # ``` {lineNos=true}
    # ```
    lineNos: false
    lineNumbersInTable: true
    # false means use external CSS file
    noClasses: false
    noHl: false
    # style: monokai
    tabWidth: 4

    

# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
