baseURL: "https://ninanikiforova.org/" 
title: Nina Nikiforova
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

social:
    twitter: nikiforovannina

taxonomies:
    tag: tags 

params:
    description: "Hi! I'm a fourth-year PhD student in Economics at Bocconi University. My research interests lie in the fields of political economy and applied industrial organization." 
    author: Nina Nikiforova 
    author: Nina Nikiforova
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","courses","design"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Nina Nikiforova
          subtitle: | 
              Hi!
              I'm a fourth-year PhD student in Economics at Bocconi University. My research interests lie in the fields of political economy and applied industrial organization. 
              
              
              
              You can reach me at <a href="mailto:nina.nikiforova@phd.unibocconi.it">**nina.nikiforova@phd.unibocconi.it**</a>
      
              _____
              My CV is **[HERE](cv.pdf)**
          author: Nina Nikiforova 
          imageUrl: "/IMAGE4.jpg"
          #imageWidth: 160
          imageHeight: 190
          imageTitle: 
          buttons:
            - name: research
              url: /research/
            - name: contact
              url: /contact/
              
    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Nina Nikiforova"
      icon: "/apple-touch-icon.png"
      iconHeight: 35
      
      markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

